### ISSUE TITLE
How to run gitstats on OS X

### ISSUE THREAD

**Issue by alexschwarz89** [hoxu/gitstats#55]
Hello there,

just if anybody tried to run gitstats with OS X El Capitan, for me these steps worked:

- Clone gitstats repository
- Get homebrew, if you not already have 
- Install gnuplot via homebrew  ```brew install gnuplot```
- Symlink your python 2.7 installation to "python2"
 ```sudo ln -s /usr/bin/python2.7 /usr/local/bin/python2```
-  ```make install``` in repository root (xcode and developer tools are required)

**Comment by hoxu** [comment]
There is actually a head-only formula for homebrew:

https://github.com/Homebrew/homebrew-head-only/blob/master/gitstats.rb

And it goes the right way about that unfortunate python2 issue - by replacing the shebang line.

If I understand it right, you should be able to install gitstats using homebrew like this:

    brew install --HEAD homebrew/head-only/gitstats

If you can test that, let me know if it works. I should definitely cover that on the homepage.

**Comment by alexschwarz89** [comment]
Ah, I saw that but was missing the --HEAD option. I can confirm it works on OS X El Capitan. I just had to run it with sudo and link gnuplot manually. +1

**Comment by hoxu** [comment]
I confirmed the installation works also on OS X - although I didn't need to do anything with gnuplot.

Added homebrew instructions on the homepage, will close this issue.

Thanks!

**Comment by tokra** [comment]
```Warning: Use homebrew/boneyard/gitstats instead of deprecated homebrew/head-only/gitstats
Error: No available formula with the name "homebrew/boneyard/gitstats"
==> Searching for a previously deleted formula...
Warning: homebrew/boneyard is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/boneyard)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.```

**Comment by ghost** [comment]
yep same error for me.

**Comment by zz-james** [comment]
same error for me
Error: No available formula with the name "homebrew/boneyard/gitstats"

**Comment by sesam** [comment]
I got `Error: homebrew/head-only was deprecated. This tap is now empty as all its formulae were migrated.`

**Comment by sebix** [comment]
> I got `Error: homebrew/head-only was deprecated. This tap is now empty as all its formulae were migrated.`

Tried https://github.com/vifactor/repostat ?
