### ISSUE TITLE
ImportError: No module named gitstats on Windows

### ISSUE THREAD

**Issue by fracz** [hoxu/gitstats#85]
```
File "C:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named gitstats
```

**Comment by fracz** [comment]
Solution: rename `gitstats` to `gitstats.py` and everything works.

**Comment by lensmartProject** [comment]
Hi Fracz i need help i am getting same error ImportError:NO module named gitstats buth after making gitstats to gitstats.py then m getting another error can't open gitstats python/python.exe error
